[package]
name = "ebpf-service"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <miguel@fleek.xyz>"]

[dependencies]
anyhow = { version = "1.0", optional = true }
aya = { git = "https://github.com/aya-rs/aya", rev = "e5d107d", features = ["async_tokio"], optional = true }
aya-log = { git = "https://github.com/aya-rs/aya", rev = "e5d107d", optional = true }
bytes = { version = "1.4", optional = true }
common = { path = "../common", features = ["userspace"], optional = true }
notify = { version = "6.1"}
libc = { version = "0.2", optional = true }
log = { version = "0.4", optional = true }
once_cell = "1.19"
resolved-pathbuf = { path = "../../../lib/resolved-pathbuf" }
tokio = { version = "1.32", features = ["macros", "rt", "rt-multi-thread", "net", "sync", "fs", "io-util"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["client"]
client = ["bytes", "log", "tokio", "anyhow"]
server = ["aya/async_tokio", "aya-log", "bytes", "libc", "tokio", "log", "anyhow", "common"]
