[package]
name = "lightning-origin-http"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affair.workspace = true
anyhow.workspace = true
lightning-interfaces = { path = "../interfaces" }
reqwest = "0.11"
serde.workspace = true
