[package]
name = "fleek-service-ipfs-fetcher"
version.workspace = true
edition.workspace = true

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true

[dev-dependencies]
lightning-handshake = { path = "../../core/handshake" }
arrayref = "0.3.7"
cid = "0.10"
