[package]
name = "lightning-rpc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
axum.workspace = true
tower-http = { version = "0.4", features = ["cors"] }
http = "0.2"
anyhow.workspace = true
jsonrpc-v2.workspace = true
serde.workspace = true
async-trait.workspace = true
serde_json.workspace = true
bincode.workspace = true
tokio.workspace = true
infusion.workspace = true
autometrics.workspace = true
tracing.workspace = true
affair.workspace = true
fleek-crypto.workspace = true
hp-fixed.workspace = true
ethers = "2.0.10"
ruint = { version = "1.10", features = ["num-bigint", "serde"] }

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
lightning-application = { path = "../application" }
lightning-fetcher = { path = "../fetcher" }
lightning-blockstore = { path = "../blockstore" }
lightning-blockstore-server = { path = "../blockstore-server" }
lightning-origin-ipfs = { path = "../origin-ipfs" }
lightning-signer = { path = "../signer" }
lightning-notifier = { path = "../notifier" }
lightning-pool = { path = "../pool" }
lightning-rep-collector = { path = "../rep-collector" }
