[package]
name = "common"
version = "0.0.0"
edition = "2021"

[features]
default = []
userspace = ["aya"]

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", rev = "e5d107d", features = ["default"], optional=true }
