[package]
name = "fleek-service-fetcher"
version = "0.0.1"
edition.workspace = true

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
arrayref = "0.3.7"

[dev-dependencies]
lightning-handshake = { path = "../../core/handshake" }
cid = "0.11"
hex = "0.4"
