[package]
name = "tea"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <miguel@fleek.xyz>"]

[dependencies]
anyhow = "1.0"
aya = { git = "https://github.com/aya-rs/aya", features = ["async_tokio"] }
aya-log = { git = "https://github.com/aya-rs/aya" }
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.11"
libc = "0.2"
log = "0.4"
tokio = { version = "1.28", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

[[bin]]
name = "xdp-lightning-app"
path = "src/bin/xdp_lightning_app.rs"
