[package]
name = "lightning-node"
version = "0.1.0"
edition = "2021"
default-run = "lightning-node"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
tokio.workspace = true
resolved-pathbuf.workspace = true
log.workspace = true
infusion.workspace = true
fleek-crypto.workspace = true
serde.workspace = true
lightning-node = { path = "../node" }
lightning-interfaces = { path = "../interfaces" }
lightning-signer = { path = "../signer" }
clap = { version = "4.4.2", features = ["derive"] }
log4rs = { version = "1.2.0", features = [
  "rolling_file_appender",
  "compound_policy",
  "size_trigger",
  "fixed_window_roller",
  "gzip",
] }
tracing = "0.1"
