[package]
name = "lightning-origin-muxer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affair.workspace = true
anyhow.workspace = true
derive_more = "0.99"
lightning-interfaces = { path = "../interfaces" }
lightning-origin-http = { path = "../origin-http" }
multiaddr = "0.17.1"
serde.workspace = true
tokio.workspace = true

