[package]
name = "lightning-node"
version = "0.1.0"
edition = "2021"

[dependencies]
lightning-interfaces = { path = "../interfaces" }
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
workspace-hack = { version = "0.1", path = "../../etc/workspace-hack" }
