[package]
name = "fleek-service-ping-example"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
lazy_static = "1.4"
hex-literal = "0.4.1"
log.workspace = true
arrayref = "0.3"
tokio = { version = "1.32", features = ["sync"] }
dashmap = "5.5"
fxhash = "0.2"
