[package]
name = "lightning-broadcast"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
anyhow.workspace = true
arrayref = "0.3.7"
async-trait.workspace = true
bytes = "1.4.0"
tokio.workspace = true
tokio-util.workspace = true
fleek-crypto = { path = "../../lib/fleek-crypto" }
ink-quill = { path = "../../lib/ink-quill" }
lightning-interfaces = { path = "../interfaces" }
lightning-metrics = { path = "../metrics" }
dashmap = "5.5.0"
mini-moka = "0.10.2"
tracing = "0.1.37"
fxhash = "0.2"
futures = "0.3"
affair.workspace = true
infusion.workspace = true
derive_more = "0.99"
im = "15.1"
smallvec = "1.11.0"
ta = "0.5.0"
log.workspace = true
rand.workspace = true
netkit.workspace = true

[dev-dependencies]
lightning-application = { path = "../application" }
lightning-signer = { path = "../signer" }
lightning-topology = { path = "../topology" }
lightning-notifier = { path = "../notifier" }
mock = { path = "../mock" }
