[package]
name = "fleek-service-js-poc"
version = "0.0.1"
edition.workspace = true

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
blake3-tree = { path = "../../lib/blake3-tree" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
fleek-crypto.workspace = true
arrayref = "0.3"
triomphe = "0.1"
serde.workspace = true
serde_json.workspace = true
deno_core = "0.232"
hex = "0.4"
cid = "0.11"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }

[dev-dependencies]
lightning-schema = { path = "../../core/schema" }

[[bin]]
name = "fn-service-1"
path = "src/bin.rs"
