[package]
name = "fleek-service-js-poc"
version = "0.0.1"
edition.workspace = true

[dependencies]
fn-sdk = { path = "../../lib/sdk" }
blake3-tree = { path = "../../lib/blake3-tree" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
fleek-crypto.workspace = true
arrayref = "0.3"
triomphe = "0.1"
serde.workspace = true
serde_json.workspace = true
hex = "0.4"
cid = "0.11"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }

# Deno core + webapi extensions
deno_core = "0.256"
deno_webidl = "0.136"
deno_console = "0.136"
deno_url = "0.136"
deno_web = "0.167"
deno_fetch = "0.160"
deno_crypto = "0.150"
deno_canvas = "0.5.0"
deno_webgpu = "0.103"

[dev-dependencies]
lightning-schema = { path = "../../core/schema" }

[build-dependencies]
deno_core = "0.256"
deno_webidl = "0.136"
deno_console = "0.136"
deno_url = "0.136"
deno_web = "0.167"
deno_fetch = "0.160"
deno_crypto = "0.150"
deno_canvas = "0.5.0"
deno_webgpu = "0.103"

[[bin]]
name = "fn-service-1"
path = "src/bin.rs"
