epoch_start = 1693842663839                                          # about 5 o clock 8-28-2023
epoch_time = 1800000                                                  # 1 hour
committee_size = 10
min_stake = 1000
eligibility_time = 1
lock_time = 5
protocol_share = 0
node_share = 80
service_builder_share = 20
max_inflation = 10
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460                                                 # 1460 days(epoch) meaning 4 years
supply_at_genesis = 1000000                                          # set to 1 million for testing, to be determined when initial allocations are set
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"

#node0 -nyc
[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "Hs+AR9H0OqhpjqrprWmQIU/ez9iwrNCieggooeCBu9c="
consensus_public_key = "pgGrPImLlRMaKF/3vfrwCtHzooHROu1vYA0dTHF9W+scNo28ya1f4JW5KoX0pMGXFnf+lOH295VPtvk/MS9lbMEnNWsULM0h3l9qhGYZ6ohNxeGEHfhwSCmsjKaulVRz"
worker_public_key = "Hs+AR9H0OqhpjqrprWmQIU/ez9iwrNCieggooeCBu9c="
primary_domain = "159.89.177.141"
worker_domain = "159.89.177.141"
ports.primary = 18000
ports.worker = 18101
ports.mempool = 18102
ports.rpc = 4069
ports.pool = 4200
ports.dht = 8101
ports.handshake = 6969
ports.blockstore = 4211
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

# node 1- nyc
[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "MxxdANeu6aZ444qLce9lbQF+a8a+cmZktZpdDIc1xZs="
consensus_public_key = "oXG6+uiSY5b+gYrjPxB0gq2R9x00xwOCVyOom6cBQFM7rGQg+vJj/VAoVFI27AWcFMisqQ7zImnWkSylvw2gsErTu1c3temcVe0lfyHUAsTi00/HMEg9n+zoGwhRE0Tm"
worker_public_key = "MxxdANeu6aZ444qLce9lbQF+a8a+cmZktZpdDIc1xZs="
primary_domain = "159.65.254.159"
worker_domain = "159.65.254.159"
ports.primary = 18000
ports.worker = 18101
ports.mempool = 18102
ports.rpc = 4069
ports.pool = 4200
ports.dht = 8101
ports.handshake = 6969
ports.blockstore = 4211
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

#node3- singapore
[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "31yaXGupsoiFYupCK5G2nqPYOfFasuFBE4OiJDkbVyc="
consensus_public_key = "tXg14fTJUMgRd8LoVORAoH0YRWHxX3pap709dr6uOoBVsQBapcP4IYLSfl05e4iRBQE+WOuisBxmr3wEjWKzkHtxzhK18TYbS1X3NKVwrMzIqnxmFj7RaVsrN3BMMNCk"
worker_public_key = "31yaXGupsoiFYupCK5G2nqPYOfFasuFBE4OiJDkbVyc="
primary_domain = "159.223.34.196"
worker_domain = "159.223.34.196"
ports.primary = 18000
ports.worker = 18101
ports.mempool = 18102
ports.rpc = 4069
ports.pool = 4200
ports.dht = 8101
ports.handshake = 6969
ports.blockstore = 4211
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

#node 2 fra
[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "fycnA7tycZyhOLb+RVgD/2H6OXzWwjAehM4ZgTVLIz0="
consensus_public_key = "hi7SRlOPxV8WRajfwXGWNObWl2kenZHHKOXV6RN0kE/pSC/tzYtmP7wwYqiVIlw2EAm16j/N7sVgmGXW30RouXp+E0v52M9mkhX+Zoyk0i4FPRoEQsYeSmbueHon8PzR"
worker_public_key = "fycnA7tycZyhOLb+RVgD/2H6OXzWwjAehM4ZgTVLIz0="
primary_domain = "165.22.88.71"
worker_domain = "165.22.88.71"
ports.primary = 18000
ports.worker = 18101
ports.mempool = 18102
ports.rpc = 4069
ports.pool = 4200
ports.dht = 8101
ports.handshake = 6969
ports.blockstore = 4211
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

#node 4 - sanfran
[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "XsE9KtedDRUGv22MLHvy8qcc52QsWGWJYY1LBnWhglg="
consensus_public_key = "qYfukFBS+GmNMLVCh4B+3wfeVwVzPaUhAwYA0zdZGMmG8XJNslNDsjV/ORoGMJMHBH4PAwmQMNw+haI2rx7lgOBVR0zuj810Fr6dhJa8gmsQMsrpMQ6E1Uk91PcnphU8"
worker_public_key = "XsE9KtedDRUGv22MLHvy8qcc52QsWGWJYY1LBnWhglg="
primary_domain = "68.183.175.80"
worker_domain = "68.183.175.80"
ports.primary = 18000
ports.worker = 18101
ports.mempool = 18102
ports.rpc = 4069
ports.pool = 4200
ports.dht = 8101
ports.handshake = 6969
ports.blockstore = 4211
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

#node 5 - nyc (matthias)
[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "zBmZaycvQsdFRfe0p5Rig/KgyYPD4yNKQTPDo7JrugM="
consensus_public_key = "jGzCgwTbk9XUWrivDImX7PPkUvKtU95MLjaSUmHaqXsxuvvllpF0KTE/BLdd6GIXGF+yjthlc+dQgSVvO77QHRdY9leXBOGT+6JTUKZZQkwCpv/DJVJJ5QGxradN/fjE"
worker_public_key = "zBmZaycvQsdFRfe0p5Rig/KgyYPD4yNKQTPDo7JrugM="
primary_domain = "167.71.102.115"
worker_domain = "167.71.102.115"
ports.primary = 18000
ports.worker = 18101
ports.mempool = 18102
ports.rpc = 4069
ports.pool = 4200
ports.dht = 8101
ports.handshake = 6969
ports.blockstore = 4211
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true


[[service]]
id = 0
owner = "0xDC0A31F9eeb151f82BF1eE6831095284fC215Ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166BDbf530a256d7c92Fa0a4128669aFd9B9F"
commodity_type = "Compute"


[[account]]
public_key = "0x959807B8D94B324A74117956731F09E2893aCd72"
flk_balance = 100
stables_balance = 100
bandwidth_balance = 100

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 0.2

[rep_scores]

[total_served]

[current_epoch_served]
