chain_id = 1337
epoch_start = 1708023220756
epoch_time = 60000
committee_size = 4
min_stake = 1000
eligibility_time = 1
lock_time = 5
max_inflation = 10
protocol_share = 0
node_share = 80
service_builder_share = 20
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460
supply_at_genesis = 1000000
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"

[[node_info]]
owner = "0xf92e239bc1ade3f5b98994fbdcaa99657ce356d2"
primary_public_key = "8ZCBNU5PgsnLGAvevPPBGxABmm6B4tv1AeEnkw3X7UoA"
consensus_public_key = "oEHAAnRvJELumsC24aZU2KyQDK4M1HbqgKpE7pwFuS8s1GztsMxZgu34NhX4T6GAKGYLBrSyxWUAnVQ35WxTJ6dAdMPrbP4xQ5H4DBaGvrN9H7aGs2Q2qwb99kWRFNz9aa9"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "8ZCBNU5PgsnLGAvevPPBGxABmm6B4tv1AeEnkw3X7UoA"
genesis_committee = false

[node_info.ports]
primary = 4310
worker = 4311
mempool = 4210
rpc = 4230
pool = 4300
pinger = 4350

[node_info.ports.handshake]
http = 4220
webrtc = 4320
webtransport = 4321

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x17d4b997a7c3307586a144904d47f6ca1ab60c09"
primary_public_key = "2eH4Up8PjLDQzkdHjesvQdCJuWAxymRnHG2JJXbK3aBW"
consensus_public_key = "mUdtQMadVD27zmdf6FmmLGcXMW4KZmJfNXZUXx4nH4V3bdNtbZg99RQg17NQ36cpWwLv1iHNocW1N8d2Hj3FEAtfewYpuL7xSBYjrVAZfCuwK4gsZrAjZfMtZJukJVCtnnP"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "2eH4Up8PjLDQzkdHjesvQdCJuWAxymRnHG2JJXbK3aBW"
genesis_committee = true

[node_info.ports]
primary = 12001
worker = 12002
mempool = 12001
rpc = 12002
pool = 12003
pinger = 12004

[node_info.ports.handshake]
http = 12003
webrtc = 12005
webtransport = 12006

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x422434a0eeee9ab2b726284d4a89160a9111eabf"
primary_public_key = "BqifnTUgQEWoMvrsGDAcPKUXQJ1kdkke1WjfewQ3KoR7"
consensus_public_key = "23XQFTuR9irTsvgKgqGWB8sCDrUQKeLNw3AHEJnjqfYmmAk7ghzrA2cvvg5TBhWzXLwgSNMqQTjuzfFQcvALFTvRVRQVjf9azQ6v7t5PECHAtsyq9tnRuFC3d955u3BiPFyV"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "BqifnTUgQEWoMvrsGDAcPKUXQJ1kdkke1WjfewQ3KoR7"
genesis_committee = true

[node_info.ports]
primary = 12007
worker = 12008
mempool = 12004
rpc = 12005
pool = 12009
pinger = 12010

[node_info.ports.handshake]
http = 12006
webrtc = 12011
webtransport = 12012

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x2a390fa93ff1c42d8be1870c71abb7e83fbcce87"
primary_public_key = "BcxmPpH967oYWeW2g6a23oizz1Qo37iPkpPA92VjvvgW"
consensus_public_key = "21H1629J3SJhaqchKv6TJz3ibmK35kmK2xhNH8SWYX4TZ1dRn6iRJr1duEu23ueN5mTVLKJ9gCPzzJgrmoS1fVqNCG5vrqA2MxPiJtNLvciuWRNCkn4EYdhdh15Gsv3LJNmL"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "BcxmPpH967oYWeW2g6a23oizz1Qo37iPkpPA92VjvvgW"
genesis_committee = true

[node_info.ports]
primary = 12013
worker = 12014
mempool = 12007
rpc = 12008
pool = 12015
pinger = 12016

[node_info.ports.handshake]
http = 12009
webrtc = 12017
webtransport = 12018

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x8bc92829c521dbc579cec7e7287ae5c925a4ea1e"
primary_public_key = "CdfWybZ4vmwYZf2dyqrcCA6DhoRyhNgoL4gWaNnZ6v42"
consensus_public_key = "26iyPu1Mjm6ErXcQhjxKuzcSVzZMXoLZdcqsWHQNxYyKM8oeAmFS7ngXiKx1M2ghPVFm9ymZ4hjx51LEkYRVZKFfx3UK5xnydpWMUzfS15ts3bu8YApwGpUrKSbFG2zAwWjL"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "CdfWybZ4vmwYZf2dyqrcCA6DhoRyhNgoL4gWaNnZ6v42"
genesis_committee = true

[node_info.ports]
primary = 12019
worker = 12020
mempool = 12010
rpc = 12011
pool = 12021
pinger = 12022

[node_info.ports.handshake]
http = 12012
webrtc = 12023
webtransport = 12024

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[service]]
id = 0
owner = "0xdc0a31f9eeb151f82bf1ee6831095284fc215ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166bdbf530a256d7c92fa0a4128669afd9b9f"
commodity_type = "Compute"

[[account]]
public_key = "0x959807b8d94b324a74117956731f09e2893acd72"
flk_balance = "100690000000000000000"
stables_balance = 100
bandwidth_balance = 100

[client]

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 0.2

[total_served]
