chain_id = 59330
epoch_start = 1701826887509
epoch_time = 3600000
committee_size = 6
min_stake = 1000
eligibility_time = 1
lock_time = 5
protocol_share = 0
node_share = 80
service_builder_share = 20
max_inflation = 10
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460                                                 # 1460 days(epoch) meaning 4 years
supply_at_genesis = 1000000                                          # set to 1 million for testing, to be determined when initial allocations are set
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "FsasFxDeFSKoSkmFRmrWExu9RveYopD6Kaomv9LM8Yt6"
consensus_public_key = "ydWVy9Y8HcrP9boLNVuisJ2PLi5rPJj6sxE3xdB1J2NAhNHPpx7UykN2aRxbwRbwXXV3kui62LKEvKMTN1fd4cYSJvAGd1kuL73ZRtN74QvbSVzMDNYfmbvdg2gyzHwAQvd"
worker_public_key = "FsasFxDeFSKoSkmFRmrWExu9RveYopD6Kaomv9LM8Yt6"
primary_domain = "174.138.82.23"
worker_domain = "174.138.82.23"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.dht = 4340
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "HrnubKpK8zVpNtk9TC7TTZo8oHuX3AUKJh26KtGb67QE"
consensus_public_key = "ziVNcbUzKf6iyM3fijFoZYytSDMSLa9FsU9wzW8xVJx9AH4beeTiSXfMbanS7KjtVeJH3g2zU4FM3KGs1UScTz4VKy3bh996WgdCkf6efuPsyKkxtxa4coz4sXvFkSD8SCp"
worker_public_key = "HrnubKpK8zVpNtk9TC7TTZo8oHuX3AUKJh26KtGb67QE"
primary_domain = "128.199.129.231"
worker_domain = "128.199.129.231"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.dht = 4340
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "8A3Z19Ns3dVvDzP8U6bp8EQUgpn444ToxHQfzbyKCQX7"
consensus_public_key = "26ztHQEZrp52E6mjNjfLeJJneBtApEmec8399BboBzT2six6szt9UJfdztFq2jgqGppBSk56i4dkvU6yGHu96bPziCdSqqpqxnwYwtQZCCi6LPj1YemQjeqpsQztd1P4uVDV"
worker_public_key = "8A3Z19Ns3dVvDzP8U6bp8EQUgpn444ToxHQfzbyKCQX7"
primary_domain = "134.209.207.15"
worker_domain = "134.209.207.15"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.dht = 4340
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "6UZCSVNWy6ZvfjbdddVg15Ln1c4BnGKEcpQoruvuEMxw"
consensus_public_key = "sNRFLsNymbgG7JAF81stXgnNw1QrTAgxx7bBNYdq2Cx2cAnjVr1kURGeENSURJXK7DFqFPbjBhiT9NC6TRtVCqFs7p2wHsAUJj7CNUMYB3JhpJjf8Cuu2R1RE5ttwAK4s4D"
worker_public_key = "6UZCSVNWy6ZvfjbdddVg15Ln1c4BnGKEcpQoruvuEMxw"
primary_domain = "161.35.208.183"
worker_domain = "161.35.208.183"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.dht = 4340
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "BzHB41bmGWE7nT4xLTBMyjz3NCRctre6N5LoGEfwdz1N"
consensus_public_key = "pToXCRATWARvxsmaMVwRU4twv52tYaLMqoX3abB4nScXuHFnjaRjQEsGNcnGvP9XPTuHKHQLvi5UxQwoaECmSK3V9J1uLU16qhM3PFS1EodwiionSDRe5isCyfSaXRB1VKf"
worker_public_key = "BzHB41bmGWE7nT4xLTBMyjz3NCRctre6N5LoGEfwdz1N"
primary_domain = "68.183.198.190"
worker_domain = "68.183.198.190"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.dht = 4340
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "JCnPCvUzB17wt2LTkTWxq6eL6G2W48SQqUwtmmUyJ4qN"
consensus_public_key = "22prKJhy5ykg7FjoskZy2hgkusQcDssdJXsZQDcFNwjFPia4UM4AMDM43k5vGLzunyJWiZg27HkHEpz77wzCREP2Y7174itDtUGj7m8xYe5emhztiBV5QMozim3yjKB5RLzf"
worker_public_key = "JCnPCvUzB17wt2LTkTWxq6eL6G2W48SQqUwtmmUyJ4qN"
primary_domain = "64.227.136.207"
worker_domain = "64.227.136.207"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.dht = 4340
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[service]]
id = 0
owner = "0xDC0A31F9eeb151f82BF1eE6831095284fC215Ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166BDbf530a256d7c92Fa0a4128669aFd9B9F"
commodity_type = "Compute"

[[account]]
public_key = "0x959807B8D94B324A74117956731F09E2893aCd72"
flk_balance = "100690000000000000000"
stables_balance = 100
bandwidth_balance = 100

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 0.2

[rep_scores]

[total_served]

[current_epoch_served]
