chain_id = 1337
epoch_start = 1708023943522
epoch_time = 60000
committee_size = 4
min_stake = 1000
eligibility_time = 1
lock_time = 5
max_inflation = 10
protocol_share = 0
node_share = 80
service_builder_share = 20
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460
supply_at_genesis = 1000000
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"

[[node_info]]
owner = "0x0981b84cd4f2f48dd6fb016756a776620a5d4e54"
primary_public_key = "8ZCBNU5PgsnLGAvevPPBGxABmm6B4tv1AeEnkw3X7UoA"
consensus_public_key = "oEHAAnRvJELumsC24aZU2KyQDK4M1HbqgKpE7pwFuS8s1GztsMxZgu34NhX4T6GAKGYLBrSyxWUAnVQ35WxTJ6dAdMPrbP4xQ5H4DBaGvrN9H7aGs2Q2qwb99kWRFNz9aa9"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "8ZCBNU5PgsnLGAvevPPBGxABmm6B4tv1AeEnkw3X7UoA"
genesis_committee = false

[node_info.ports]
primary = 4310
worker = 4311
mempool = 4210
rpc = 4230
pool = 4300
pinger = 4350

[node_info.ports.handshake]
http = 4220
webrtc = 4320
webtransport = 4321

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x869d649dd01b82075466debc1fc2ccdbe652f13f"
primary_public_key = "AnJGiTEWmzibhebz1EQesJwZ9iL9Sn4EbCi8awhtLLnX"
consensus_public_key = "tcMyxagczasSUMW1YKWnW1b5T2rDGC1dgW3narUVs2QSyjzFewBzN6PX8VZn7PpR227ob3fXTFvZeHiHirhrLGjPT3Q11Gn2VyypuQPJpS1ozNFXbc1fhp2b219Nc1i7KK1"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "AnJGiTEWmzibhebz1EQesJwZ9iL9Sn4EbCi8awhtLLnX"
genesis_committee = true

[node_info.ports]
primary = 12001
worker = 12002
mempool = 12001
rpc = 12002
pool = 12003
pinger = 12004

[node_info.ports.handshake]
http = 12003
webrtc = 12005
webtransport = 12006

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x1b063e036d182fd36ea00e78b72732ae227c25bf"
primary_public_key = "2TWsU25zB2qt3nFXoFiQVbFSXVnXK4ZgoH1jHMpgxWh4"
consensus_public_key = "2253PiHtGyugpBr7HaaiACW64iVFWpi87ooWVxwmHV8pTuNAGk5ZDkHcBqJcbBSDsb9HWVBTk9giwkkuXCrnr2gHY5nrQtGbZ5hnAL3uvUP1i7jZ79NhB2GD9vCXJAVs4S3L"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "2TWsU25zB2qt3nFXoFiQVbFSXVnXK4ZgoH1jHMpgxWh4"
genesis_committee = true

[node_info.ports]
primary = 12007
worker = 12008
mempool = 12004
rpc = 12005
pool = 12009
pinger = 12010

[node_info.ports.handshake]
http = 12006
webrtc = 12011
webtransport = 12012

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0xbb8a9b33563a01a611d1f6381fa4162ab7ada154"
primary_public_key = "BKTVVjbUH9zp1iTmTkeRx9dgcMPhraATCA3SSx3YUdUD"
consensus_public_key = "sHwVztSZpaUuxxnx7wJZEfv8aHoXYKjKY2VqW1v9EMJ1NPg69YpuwbeonnUP2owSQgV8zSZhHYJLmjK939my3aSDjDjSRcgKeupWacfAfk7v5zkVcLxCPZmrqs9E3eSUcXh"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "BKTVVjbUH9zp1iTmTkeRx9dgcMPhraATCA3SSx3YUdUD"
genesis_committee = true

[node_info.ports]
primary = 12013
worker = 12014
mempool = 12007
rpc = 12008
pool = 12015
pinger = 12016

[node_info.ports.handshake]
http = 12009
webrtc = 12017
webtransport = 12018

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[node_info]]
owner = "0x88925cdaf78c7d546b4463d7f5b8279473e47bcf"
primary_public_key = "6c1zgNxWUzb4uyUQam9jthPXQ3CCpvAX86bh1ULm5ZML"
consensus_public_key = "21wF6Hhz4wUaBWASVMYPksJGke5tu6R8RvVKdbUswDEcdHxvX2owKPFuCJq2jZLJt2BkkG8EcWUV6oaMUPYjzDGCabxD8eaS7qi5YqzhRMFaAfwDrYirPsjVdeiEdEBfjzCU"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
worker_public_key = "6c1zgNxWUzb4uyUQam9jthPXQ3CCpvAX86bh1ULm5ZML"
genesis_committee = true

[node_info.ports]
primary = 12019
worker = 12020
mempool = 12010
rpc = 12011
pool = 12021
pinger = 12022

[node_info.ports.handshake]
http = 12012
webrtc = 12023
webtransport = 12024

[node_info.stake]
staked = "1000000000000000000000"
stake_locked_until = 0
locked = "0"
locked_until = 0

[[service]]
id = 0
owner = "0xdc0a31f9eeb151f82bf1ee6831095284fc215ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166bdbf530a256d7c92fa0a4128669afd9b9f"
commodity_type = "Compute"

[[account]]
public_key = "0x959807b8d94b324a74117956731f09e2893acd72"
flk_balance = "100690000000000000000"
stables_balance = 100
bandwidth_balance = 100

[client]

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 0.2

[total_served]
