name: Docker (Build & GHCR publish)

on:
  push:
    branches:
      - testnet-**
      - chore/dockerfile-support
    paths:
      - core/**
      - etc/**
      - lib/**
      - services/**
      - Cargo.toml
      - .github/workflows/docker-publish.yml
      - Dockerfile
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  LIGHTNING_IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Docker build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.LIGHTNING_IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch

      - name: Build and push Docker image
        id: lightning-build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # TIAS the experimental https://github.com/moby/buildkit#github-actions-cache-experimental
          cache-from: type=gha
          cache-to: type=gha,mode=max
