name: docker-build-push

on:
  push:
    branches:
      - "testnet-**"
    paths:
      - "core/**"
      - "etc/**"
      - "lib/**"
      - "services/**"
      - "Cargo.toml"
      - ".github/workflows/docker-publish.yml"
      - "Dockerfile"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  LIGHTNING_IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Docker build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: lightning-meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.LIGHTNING_IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch

      - name: Build and push Docker image
        id: lightning-build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.lightning-meta.outputs.tags }}
          labels: ${{ steps.lightning-meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          # About mode=max
          # https://github.com/moby/buildkit#--export-cache-options
          # https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
