[package]
name = "lightning-admin"
version = "0.0.0"
edition = "2021"
authors = ["M. Meier <miguel@fleek.xyz>"]
build = "build.rs"

[dependencies]
anyhow = "1.0"
aya = { git = "https://github.com/aya-rs/aya", features = ["async_tokio"] }
aya-log = { git = "https://github.com/aya-rs/aya" }
clap = { version = "4.4", features = ["derive"] }
color-eyre = "0.6.2"
common = { path = "../common", features = ["userspace"] }
ebpf-service = { path = "../service", default-features = false, features = ["client", "server"] }
env_logger = "0.11"
libc = "0.2"
lightning-tui = { path = "../tui" }
log = "0.4"
resolved-pathbuf = { path = "../../../lib/resolved-pathbuf" }
tokio = { version = "1.28", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

[build-dependencies]
vergen = { version = "8.2.6", features = [ "build", "git", "gitoxide", "cargo" ]}

[[bin]]
name = "lightning_ebpf"
path = "src/bin/lightning_ebpf.rs"
